### ISSUE TITLE
Can you create a simple example how to use the plugin with validation?

### ISSUE THREAD

**Issue by invaderhd** [Borales/yii2-phone-input#1]
I want to implemente you plugin but I'm having difficulties with validations, can you provide an example (model + view)?

**Comment by Borales** [comment]
@invaderhd ok, I will

**Comment by invaderhd** [comment]
@Borales thank you. I only need a very simples example, of an phone input that validate the number and country code.

**Comment by Borales** [comment]
@invaderhd sorry for the delay. Check the latest update in docs section
