### ISSUE TITLE
Masks?

### ISSUE THREAD

**Issue by caxopog** [Borales/yii2-phone-input#18]
Hi guys, thanks for the extension!

It's not the bug, but feature request.
Is it possible, to not only display phone format as input's placeholder, but make input masked with this country's format? For example, if i chose Russia, i'll enter phone with mask "(999) 999-9999"

Sry for bad english.

**Comment by Borales** [comment]
@caxopog I'll try to check it, sure

**Comment by Borales** [comment]
@caxopog sorry for the delay.
You can check masked input here https://github.com/jackocnr/intl-tel-input/issues/500

Since this is a plugin feature request (not wrapper-related) - I'm closing this issue.

Thank you.
