### ISSUE TITLE
Asset lib/libphonenumber/build/utils.js has been moved

### ISSUE THREAD

**Issue by lars-t** [Borales/yii2-phone-input#2]
lib/libphonenumber/build/utils.js has been moved to build/js/utils.js
Look at https://github.com/jackocnr/intl-tel-input/commit/59ee922d26045fe1d65c4da64f2e5aaa438cbe93
PhoneInputAsset should be adjusted according to that.

**Comment by Borales** [comment]
Fixed by #3
