### ISSUE TITLE
Composer update giving errors

### ISSUE THREAD

**Issue by deadmantfa** [Borales/yii2-phone-input#21]
Hi,

Received this error while running composer update in my project

`[Composer\DependencyResolver\SolverProblemsException]                                                               
    Problem 1                                                                                                         
      - Installation request for borales/yii2-phone-input * -> satisfiable by borales/yii2-phone-input[dev-master].   
      - borales/yii2-phone-input dev-master requires giggsey/libphonenumber-for-php ^7 -> no matching package found.  
  Potential causes:                                                                                                   
   - A typo in the package name                                                                                       
   - The package is not available in a stable-enough version according to your minimum-stability setting              
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.                               
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.       `

**Comment by Borales** [comment]
@deadmantfa I will check it.

Do you use any custom repositories for your composer.json?

**Comment by deadmantfa** [comment]
I do use a lot of third-party extensions like yours 

I am adding my composer.json file here

{
  "name": "BananaBandy",
  "description": "BananaBandy Application",
  "keywords": ["yii2", "framework", "advanced", "project template"],
  "homepage": "https://www.bananabandy.com/",
  "type": "project",
  "license": "BSD-3-Clause",
  "support": {
    "issues": "https://www.bananabandy.com/contactus"
  },
  "minimum-stability": "dev",
  "require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "2.*",
    "yiisoft/yii2-bootstrap": "*",
    "yiisoft/yii2-swiftmailer": "*",
    "yiisoft/yii2-authclient": "*",
    "yiisoft/yii2-imagine": "2.0.0",
    "yiisoft/yii2-elasticsearch": "~2.0.0",
    "amnah/yii2-user": "^4.0",
    "facebook/graph-sdk": "*",
    "google/apiclient": "1.1.2",
    "aws/aws-sdk-php": "*",
    "yurkinx/yii2-image": "dev-master",
    "ksubileau/color-thief-php": "*",
    "get-stream/stream": "2.2.9",
    "borales/yii2-elasticsearch-behavior": "*",
    "nickcv/yii2-mandrill": "*",
    "nwtn/php-respimg": "*",
    "ps/image-optimizer": "*",
    "dmstr/yii2-adminlte-asset": "2.*",
    "funson86/yii2-setting": "*",
    "mdmsoft/yii2-admin": "2.0",
    "yiisoft/yii2-jui": "~2.0.0",
    "kartik-v/yii2-export": "*",
    "kartik-v/yii2-mpdf": "^1.0",
    "kartik-v/yii2-grid": "@dev",
    "kartik-v/yii2-widgets": "*",
    "kartik-v/yii2-date-range": "*",
    "kartik-v/yii2-checkbox-x": "1.*",
    "mrssoft/yii2-sitemap": "dev-master",
    "linslin/yii2-curl" : "*",
    "behance/api-network": "~2.0.0",
    "bower-asset/chartjs": "2.0.0",
    "kartik-v/yii2-dynagrid": "@dev",
    "asinfotrack/yii2-audittrail": "dev-master",
    "borales/yii2-phone-input": "*",
    "codemix/yii2-excelexport": "*",
    "filsh/yii2-oauth2-server": "2.0.1.x-dev",
    "mootensai/yii2-enhanced-gii": "dev-master",
    "mootensai/yii2-relation-trait": "dev-master",
    "cboden/ratchet": "0.3.*",
    "yii2mod/yii2-rbac": "*",
    "githubjeka/yii2-gui-rbac": "1.0.2"
  },
  "require-dev": {
    "yiisoft/yii2-apidoc": "2.*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*",
    "codeception/codeception": "^2.1",
    "bazilio/yii2-stubs-generator": "~1",
    "yiisoft/yii2-debug": "^2.0"
  },
  "config": {
    "process-timeout": 1800
  },
  "extra": {
    "asset-vcs-driver-options": {
      "github-no-api": true
    },
    "asset-pattern-skip-version": "(-build)",
    "asset-installer-paths": {
      "npm-asset-library": "vendor/npm",
      "bower-asset-library": "vendor/bower"
    }
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
}

**Comment by Borales** [comment]
@deadmantfa so you use this custom repository, I will check what could be wrong.

```
"repositories": [
  {
    "type": "composer",
    "url": "https://asset-packagist.org"
  }
]
```

**Comment by deadmantfa** [comment]
Oh Ok if required I shall remove it, that was just something mentioned here which I used
http://www.yiiframework.com/wiki/843/boost-composer-asset-plugin-update-speed/

Its been working fine since months never had an issue it just broke suddenly today

**Comment by Borales** [comment]
@deadmantfa no, it's not required of course. I just need to check if this repository can cause such problem.

**Comment by deadmantfa** [comment]
@Borales Cool Thanks will wait for your update. Cheers.

**Comment by ilyastuit** [comment]
> Hi,
> 
> Received this error while running composer update in my project
> 
> `[Composer\DependencyResolver\SolverProblemsException]
> Problem 1
> - Installation request for borales/yii2-phone-input * -> satisfiable by borales/yii2-phone-input[dev-master].
> - borales/yii2-phone-input dev-master requires giggsey/libphonenumber-for-php ^7 -> no matching package found.
> Potential causes:
> 
> * A typo in the package name
> * The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.
>   Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.       `

i have the same problem, how can i solve it?
