### ISSUE TITLE
libphonenumber-for-php v8 released

### ISSUE THREAD

**Issue by giggsey** [Borales/yii2-phone-input#22]
Hi,

[libphonenumber-for-php v8](https://github.com/giggsey/libphonenumber-for-php/releases/tag/8.0) has been released, and it'll be good for this project to support it going forwards.

The BC changes are:
 - Convert from PSR-0 to PSR-4
 - Remove deprecated `ShortNumberUtil`, use `ShortNumberInfo` instead
 - Deleting deprecated methods in `ShortNumberInfo` that work on strings, instead
   of phone number objects. These have been marked deprecated for months. Any
   users of these methods should call `PhoneNumberUtil::parse` first to create a
   `PhoneNumber` object, and pass this in.
 - Support semicolon as extension character while parsing phone numbers.

**Comment by Borales** [comment]
@giggsey awesome, thanks for the report, I'll do the upgrade.
