### ISSUE TITLE
it does not look good with bootstrap

### ISSUE THREAD

**Issue by michaelnguyen547** [Borales/yii2-phone-input#25]
it looks ugly with bootstrap, any suggestions to fix it ?

![2017-03-30_1659](https://cloud.githubusercontent.com/assets/436950/24529731/91357722-156a-11e7-9c01-16379ebf4819.png)

thanks

**Comment by Borales** [comment]
@michaelnguyen547 try to pass bootstrap-specific css class to this component

**Comment by TonisOrmisson** [comment]
had the same issue.
Try adding to css:
`.intl-tel-input {width: 100%;}`

**Comment by michaelnguyen547** [comment]
thanks @TonisOrmisson  for the tip

for my case, i did

```
    .intl-tel-input,.intl-tel-input input {
        width: 100%;
    }

    .intl-tel-input input {
        padding: 6px 12px;
    }
```

and I also add class to input field so it shows proper format 

```
<? echo $form->field($model, 'primary_phone', ['options' => ['class' => 'col-md-3']])->widget(PhoneInput::className(), [
    'jsOptions' => [
        'preferredCountries' => ['no', 'pl', 'ua'],
    ],
    'defaultOptions' => [
        'class' => 'form-control'
    ]
]);
?>
```
![phone](https://cloud.githubusercontent.com/assets/436950/25599711/904c2ae6-2e9b-11e7-90d4-41c3df4f8653.png)

Thanks for this awesome plugin
