### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by dev-yarolsav** [Borales/yii2-phone-input#34]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - borales/yii2-phone-input 0.1.1 requires bower-asset/intl-tel-input ^11 -> no matching package found.
    - borales/yii2-phone-input 0.1.1 requires bower-asset/intl-tel-input ^11 -> no matching package found.
    - Installation request for borales/yii2-phone-input ^0.1.1 -> satisfiable by borales/yii2-phone-input[0.1.1].

**Comment by csabike2** [comment]
Hey,

try to remove bower-asset/intl-tel-input asset. I had similar issue yesterday.
My solutions was the next:

`composer remove borales/yii2-phone-input, `
then 
`composer remove bower-asset/intl-tel-input`
then
`composer install`
then
`composer require "borales/yii2-phone-input" "*"`
and finally
`composer install`

after these steps, everything worked for me.

**Comment by pptyasar** [comment]
Not working @csabike2

**Comment by Borales** [comment]
@pptyasar @csabike2 @Yarisrespect I apologize for such a delay with this issue, I'm going to fix today/tomorrow

**Comment by Borales** [comment]
@Yarisrespect @pptyasar could you please check your projects with the latest changes to `composer.json`? I'm gonna add some tests to this repo in the meantime

**Comment by Rinku786** [comment]
@Borales  Have you solved this issue? Today i've tried to install Borales/yii2-phone-input extension through composer and it's still producing errors:
![errors](https://user-images.githubusercontent.com/6859016/43899402-6c23f36a-9bff-11e8-8bb2-d9d233594f3a.png)

**Comment by classicalguss** [comment]
Hi I'm getting something similar. Any idea?

./composer.json has been updated                                                                                                                                                                                                                                                The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option                                                                                                                                                                       Loading composer repositories with package information                                                                                                                                                                                                                          Updating dependencies (including require-dev)                                                                                                                                                                                                                                   The "https://bower.herokuapp.com/packages/jquery" file could not be downloaded (HTTP/1.1 502 Bad Gateway)                                                                                                                                                                       https://bower.herokuapp.com/packages could not be fully loaded, package information was loaded from the local cache and may be out of date                                                                                                                                      Your requirements could not be resolved to an installable set of packages.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Problem 1                                                                                                                                                                                                                                                                         - borales/yii2-phone-input 0.1.2 requires bower-asset/intl-tel-input ^12 -> no matching package found.                                                                                                                                                                          - borales/yii2-phone-input 0.1.1 requires bower-asset/intl-tel-input ^11 -> no matching package found.                                                                                                                                                                          - borales/yii2-phone-input 0.1.0 requires bower-asset/intl-tel-input ^10 -> no matching package found.                                                                                                                                                                          - borales/yii2-phone-input 0.0.5 requires bower-asset/intl-tel-input * -> no matching package found.                                                                                                                                                                            - borales/yii2-phone-input 0.0.4 requires bower-asset/intl-tel-input * -> no matching package found.                                                                                                                                                                            - borales/yii2-phone-input 0.0.3 requires bower-asset/intl-tel-input * -> no matching package found.                                                                                                                                                                            - borales/yii2-phone-input 0.0.2 requires bower-asset/intl-tel-input * -> no matching package found.                                                                                                                                                                            - borales/yii2-phone-input 0.0.1 requires bower-asset/intl-tel-input * -> no matching package found.                                                                                                                                                                            - Installation request for borales/yii2-phone-input * -> satisfiable by borales/yii2-phone-input[0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.1.1, 0.1.2].                                                                                                                                                                                                                                                                                                                                                                                                   Potential causes:                                                                                                                                                                                                                                                                - A typo in the package name                                                                                                                                                                                                                                                    - The package is not available in a stable-enough version according to your minimum-stability setting                                                                                                                                                                             see  for more details.                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Read  for further common problems.
--

**Comment by Borales** [comment]
@Rinku786 @classicalguss have you tried using this service https://asset-packagist.org/ ?

**Comment by bologer** [comment]
Same issue: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - borales/yii2-phone-input 0.2.1 requires bower-asset/intl-tel-input ^16 -> no matching package found.
    - borales/yii2-phone-input 0.1.2 requires bower-asset/intl-tel-input ^12 -> no matching package found.
    - borales/yii2-phone-input 0.1.1 requires bower-asset/intl-tel-input ^11 -> no matching package found.
    - borales/yii2-phone-input 0.1.0 requires bower-asset/intl-tel-input ^10 -> no matching package found.
    - borales/yii2-phone-input 0.0.5 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.4 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.3 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.2 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.1 requires bower-asset/intl-tel-input * -> no matching package found.
    - Installation request for borales/yii2-phone-input * -> satisfiable by borales/yii2-phone-input[0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.1.1, 0.1.2, 0.2.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```


**Edit**: adding repo entry from https://asset-packagist.org/ helped, thanks

**Comment by Borales** [comment]
Is this issue still relevant?

**Comment by bologer** [comment]
@Borales no

**Comment by alexander-ronin** [comment]
I've tried to install Borales/yii2-phone-input extension through composer and it's show errors:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - borales/yii2-phone-input 0.3.0 requires bower-asset/intl-tel-input ^16 -> no matching package found.
    - borales/yii2-phone-input 0.2.1 requires bower-asset/intl-tel-input ^16 -> no matching package found.
    - borales/yii2-phone-input 0.1.2 requires bower-asset/intl-tel-input ^12 -> no matching package found.
    - borales/yii2-phone-input 0.1.1 requires bower-asset/intl-tel-input ^11 -> no matching package found.
    - borales/yii2-phone-input 0.1.0 requires bower-asset/intl-tel-input ^10 -> no matching package found.
    - borales/yii2-phone-input 0.0.5 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.4 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.3 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.2 requires bower-asset/intl-tel-input * -> no matching package found.
    - borales/yii2-phone-input 0.0.1 requires bower-asset/intl-tel-input * -> no matching package found.
    - Installation request for borales/yii2-phone-input * -> satisfiable by borales/yii2-phone-input[0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.1.1, 0.1.2, 0.2.1, 0.3.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```
