### ISSUE TITLE
Link to $jsOptions options 

### ISSUE THREAD

**Issue by bologer** [Borales/yii2-phone-input#38]
Please add some documentation where to get list of settings for JS widget in `$jsOptions` doc block  property for `PhoneInput` class. 

Such as: 

```php 
/**
 * @link https://github.com/jackocnr/intl-tel-input#options More information about JS-widget options.
 * @var array Options of the JS-widget
 */
public $jsOptions = [];
```

Thanks in advance.

**Comment by Borales** [comment]
@bologer  Done
