### ISSUE TITLE
customPlaceholder

### ISSUE THREAD

**Issue by MichalNemec** [Borales/yii2-phone-input#48]
Hello, how to have custom placeholder in form widget?
this does not work at all.
```
'jsOptions' => [
        'preferredCountries' => Yii::$app->params['preferredCountries'],
        'customPlaceholder' => ' function(...){return "foobar";} '
    ],
```

**Comment by Borales** [comment]
@MichalNemec `customPlaceholder` where did you get that?

**Comment by MichalNemec** [comment]
https://github.com/jackocnr/intl-tel-input

```
customPlaceholder: function(selectedCountryPlaceholder, selectedCountryData) {
  return "e.g. " + selectedCountryPlaceholder;
}
```

**Comment by Borales** [comment]
@MichalNemec `customPlaceholder' => ' function(...){return "foobar";} ` - I believe such code will render your string as is, but you should be using [this class](https://github.com/yiisoft/yii2/blob/master/framework/web/JsExpression.php) class, try it.

**Comment by MichalNemec** [comment]
Ah, okay, thank you
