### ISSUE TITLE
intl-tel-input have new version 13

### ISSUE THREAD

**Issue by hooman-pro** [Borales/yii2-phone-input#51]
https://github.com/jackocnr/intl-tel-input/releases

I need it for our project because client validation use intl-tel-input and new version have all number format. in this repo last relase it use version 11 of init-tel-input!!

---------------
I see in master composer.json it use version 12 . if it is ok , why you dont relase a new version for this repo.

sorry for my bad english

**Comment by Borales** [comment]
@hooman-pro I'd need to test it first. But if you need intl-tel-input version 12 - I can do it right now, please let me know.

**Comment by hooman-pro** [comment]
Yes, please. 
I check version 12.4.0 and it is ok with new numbers i need

**Comment by Borales** [comment]
@hooman-pro released
