### ISSUE TITLE
Validation setup

### ISSUE THREAD

**Issue by i-panov** [Borales/yii2-phone-input#56]
Please tell me how to make it accept mobile numbers without a plus at the beginning? 
For example, our Russian numbers start with +7 (for example, `+7 (495) 1234567`), 
but can start with 8 (for example, `8 (495) 1234567` - it works inside the country).

**Comment by Borales** [comment]
@i-panov please try to refer to the original libraries, this is just a wrapper package for them

**Comment by i-panov** [comment]
@Borales ok
