### ISSUE TITLE
Any Ivory Coast phone numbers are incorrect

### ISSUE THREAD

**Issue by shurper** [Borales/yii2-phone-input#72]
Hello!
Some public information:
The "Autorité de Régulation des Télécommunications/TIC de Côte d’Ivoire" (ARTCI) hereby announced the modification of the national numbering plan of Côte d’Ivoire, from eight (8) to ten (10) digits, effective 31 January 2021 in Côte d’Ivoire.

Phone example, +225 01 9876 5478

**Comment by Borales** [comment]
@shurper for format validation fully relies on https://github.com/giggsey/libphonenumber-for-php
