### ISSUE TITLE
Two widget on one input form

### ISSUE THREAD

**Issue by Kravalg** [Borales/yii2-phone-input#8]
Good afternoon. How can I have one form field to hang two of your widget and https://github.com/unclead/yii2-multiple-input ?

**Comment by Kravalg** [comment]
Sorry, inattentively read the documentation, that's a working example:
<?= $form->field($model, 'schedule')->widget(MultipleInput::className(), [
    'limit' => 4,
    'columns' => [
        [
            'name'  => 'day',
            'type'  => \kartik\date\DatePicker::className(),
            'title' => 'Day',
            'value' => function($data) {
                return $data['day'];
            },
            'items' => [
                '0' => 'Saturday',
                '1' => 'Monday'
            ],
            'options' => [
                'pluginOptions' => [
                    'format' => 'dd.mm.yyyy',
                    'todayHighlight' => true
                ]
            ],
            'headerOptions' => [
                'style' => 'width: 250px;',
                'class' => 'day-css-class'
            ]
        ]
    ]
 ]);
?>

We should use : 'type' => PhoneInput::className(),

**Comment by Borales** [comment]
@Kravalg can you post here a working example with that plugin? Or make a PR.
I will add this to README

**Comment by Kravalg** [comment]
@Borales Oh sure
I could get them to work together, but unfortunately, refused to use your widget.
I hope that I reach your hands to help you with improving this widget.
And yet it raw and is not suitable for production.

**Comment by Kravalg** [comment]
Work example:
```
<?= $form->field($model, 'schedule')->widget(MultipleInput::className(), [
'limit' => 4,
'columns' => [
[
'name' => 'day',
'type' => \borales\PhoneInput
::className(),
'title' => 'Day',
'value' => function($data) {
return $data['day'];
},
]
]
]);
?>
```
